name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-macos:
    name: Build for macOS

    runs-on: macos-11

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip3 install docutils
          brew install make autoconf automake

      - name: Build
        run: ./build-macos.sh

      - uses: actions/upload-artifact@v3
        with:
          name: ctags-static-darwin-arm64
          path: target/darwin-arm64

      - uses: actions/upload-artifact@v3
        with:
          name: ctags-static-darwin-x86_64
          path: target/darwin-x86_64

  build-linux:
    name: Build for Linux

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            musl-tools \
            python3-docutils

      - name: Build
        run: ./build-linux.sh

      - uses: actions/upload-artifact@v3
        with:
          name: ctags-static-linux-x86_64
          path: target/linux-x86_64

  build-windows:
      name: Build for Windows

      runs-on: windows-2022

      steps:
        - uses: actions/checkout@v4

        - uses: msys2/setup-msys2@v2
          with:
            msystem: UCRT64
            update: true
            install: git make automake autoconf
            pacboy: toolchain:p python3-docutils:p jansson:p libxml2:p libyaml:p pcre2:p

        - name: Build
          shell: msys2 {0}
          run: ./build-windows.sh

        - uses: actions/upload-artifact@v3
          with:
            name: ctags-static-windows-x86_64
            path: target/windows-x86_64
