name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-macos:
    name: Build macOS

    runs-on: macos-11

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip3 install docutils
          brew install make autoconf automake

      - name: Build
        run: ./build-macos.sh

      - uses: actions/upload-artifact@v3
        with:
          name: ctags-static-darwin-arm64
          path: target/darwin-arm64

      - uses: actions/upload-artifact@v3
        with:
          name: ctags-static-darwin-x86_64
          path: target/darwin-x86_64

  build-linux:
    name: Build Linux

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            musl-tools \
            python3-docutils

      - name: Build
        run: ./build-linux.sh

      - uses: actions/upload-artifact@v3
        with:
          name: ctags-static-linux-x86_64
          path: target/linux-x86_64
